// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wplllvlflaoeacktwlct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbGxsdmxmbGFvZWFja3R3bGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTE5NzksImV4cCI6MjA2NDA2Nzk3OX0.mY7eAkVYcDCcBnEzZRDb0o_NL_I1PVvFifC1VuchoLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);